# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DoLzuyk84std6LHi2wVnUkP8kHxE_tF
"""



from my_functions import build_person, build_experiment

if__name__ == "__main__":
  supervisor = build_person ("Sophia", "Österle", "female", 19)
  subject = build_person ("Max", "Mustermann", "male", 25)

  experiment = build_experiment("Reaktionszeitmessung", "2025-03-22", supervisor, subject)
  print("\nExperiment-Daten:")
  for key, value in experiment.items():
    print(f"{key}: {value}")

python main.py